### ISSUE TITLE
Hello, please could you describe how to upload FW with Arduino IDE in this case?

### ISSUE THREAD

**Issue by githubmich** [KmanOz/Sonoff-HomeAssistant#1]
I really don´t know where to put those downloaded libraries. thank you very much.

**Comment by KmanOz** [comment]
https://community.home-assistant.io/t/sonoff-homeassistant-alternative-firmware-for-sonoff-switches-for-use-with-mqtt-ha/2332/57

Have a look at this discussion. It may help
