### ISSUE TITLE
Sonoff Touch

### ISSUE THREAD

**Issue by smhaller** [KmanOz/Sonoff-HomeAssistant#11]
Not a real issue but in the documentation for the Sonoff touch - just a small remark because it took me a bit till i found the solution:

4. Upload the firmware using Arduino IDE. Make sure that the selected board is "Generic ESP8285 Module" and the upload speed is 115200

and use (not the default values but):  
  Flash Mode: DOUT
  Flash Size: 1M (64k SPIFFS)

**Comment by mp3llll** [comment]
hey,

do you know if can i use also FTDI adapter with sonoff touch?

**Comment by KmanOz** [comment]
Yes you can
