### ISSUE TITLE
ESP wifi networks appearing?

### ISSUE THREAD

**Issue by Leeev** [KmanOz/Sonoff-HomeAssistant#14]
Not sure if this an issue, I've not noticed it up until now, but being tinkering with a new router which showed that I have 4 new wireless networks in the area, all called ESP_xxxxxx. 
Strangely this is also the number of Sonoff units I have doing stuff around the house. :)
They seem to drop in and out, I can ping them on 192.168.4.1 but there appears to be no other services running. Is this by design? What for? Can I turn it off?

**Comment by KmanOz** [comment]
Are you sure you;re using v1.01 firmware version. The original did have that issue.
