### ISSUE TITLE
Hello I need your help, can I?

### ISSUE THREAD

**Issue by 1043717432** [KmanOz/Sonoff-HomeAssistant#15]
I wrote a 8266 firmware control switch 3, hope that through your help handle the storage state of EEPROM, and MQTT_TOPIC can be customized, I need to customize each switch can be a noun, more hope can please help me to add DHT22 related code. I'll send you the firmware source code. Hope you can see me.

**Comment by KmanOz** [comment]
Sorry dude I hardly have time to do what I want to do so unfortunately I have to decline

**Comment by 1043717432** [comment]
ok,tks!!!
