### ISSUE TITLE
Little issue on mqtt client

### ISSUE THREAD

**Issue by khzd** [KmanOz/Sonoff-HomeAssistant#17]
Hi 
in the ino file : ESPsonoff_4CH-v1.01p
what about to change : #define MQTT_CLIENT     "Sonoff_Living_Room_v1.0pow"         // mqtt client_id (Must be unique for each Sonoff)
By some thing specific to the ESPsonoff_4CH-v1.01p ?
Cheer

**Comment by KmanOz** [comment]
It's just a name. You can call it whatever you like. I copied that from other code.
