### ISSUE TITLE
Hostname would be nice to have

### ISSUE THREAD

**Issue by donnib** [KmanOz/Sonoff-HomeAssistant#24]
Hi,
When using OTA and when you have many devices it would be nice to be able to identify the nodes using a well known hostname, i know it's possible to use `WiFi.hostname("Name")` is this something you could consider adding ?

**Comment by jgibbarduk** [comment]
[+1]
I also have a lot of Sonoff devices, it would be great to have their hostname show up in the Arduino IDE when wanting to update them OTA. Thanks.

**Comment by KmanOz** [comment]
Yes this is something I am going to add as well as some diagnostics via mqtt. Stay tuned.

**Comment by KmanOz** [comment]
Yeah I spent some time today getting the WiFi, OTA Update and MQTT username setup automatically by the ESP Chip ID. Works well and it something else you don't need to worry about. Anyway will keep at it and release another ver soon.

**Comment by KmanOz** [comment]
this is now on the new version of the firmware
