### ISSUE TITLE
Can't Upload with OTA

### ISSUE THREAD

**Issue by 1ocate** [KmanOz/Sonoff-HomeAssistant#26]
Hello 
Thank you for made this code and it's really using useful 

Already success upload with usb ttl "ESPsonoff-v1.01pOTA"
But after I want to upload with OTA have a problem...
I can see from arduino ide network port  my sonoff ip and can chose that port.
But try to upload then "[ERROR]: No response from device" message comes out.
So I want open serial monitor (from networkport) asking password but cant found it.
And Finally with connect usb ttl and open serial monitor and upload, the error message is "Begin Failed" 
Using that keyword search and search but I can't get that..  so finally asking here..

I using sonoff basic version and this is want to connect with usb ttl so hard (coz using case) 
Really want using with OTA upload.. can I get some hint?

Just now I saw issuse closed about OTA problem

"Make sure that you initially use 1M(64K SPIIFS) and then use that setting each time you update via OTA"

So I try again change 1M(64K SPIIFS) and upload but same message([ERROR]: No response from device)
or that mean first time upload using usb ttl that time also 1M(64K SPIIFS) ?

**Comment by KmanOz** [comment]
This isn't an issue with the code but rather an issue with your network and setup. Check that the port isn't being blocked on the machine you are trying to upload with, and the version of Python you are using etc. Python needs to be 2.7.x.x not version 3. Can't help much else sorry.
