### ISSUE TITLE
sonoff wifi + am2301

### ISSUE THREAD

**Issue by cipeczka** [KmanOz/Sonoff-HomeAssistant#27]
Hello!

I have classic sonoff version and want to connect am2301.
How to do it and is there HOWTO ?

Best Regards!

**Comment by KmanOz** [comment]
I have deliberately left this out of code. The connection method to the Basic Sonoff is through pins and modification to the case. It's just much easier to connect to the Sonoff TH series with a simple plug. The code is the same for both so you are free to do it on your own. Thanks
