### ISSUE TITLE
Can't get the button to work on S20

### ISSUE THREAD

**Issue by donnib** [KmanOz/Sonoff-HomeAssistant#28]
Hi,
I have flashed with 1.01pOTA and the switch works fine from HASS but i can't manually turn on / off from the button on the switch itself, have you experienced that ?

**Comment by KmanOz** [comment]
Don't have one here too test but will have soon. I'll let you know

**Comment by donnib** [comment]
Thank you, that would be cool to know, i would have guessed somebody else would have seen this problem if it was there as well known problem so either the HW is different or i did something wrong (which is hard to believe coz i didn't touch the code other than the configs.)

**Comment by KmanOz** [comment]
Hey I have a question for you. I now have one here to test. How do you get them open LOL :D

**Comment by donnib** [comment]
@KmanOz there is a screw underneath the small label on the back of it and then you pry it open.

**Comment by mitsumaui** [comment]
Looks like this has been a while - however works fine for the S20 I have just flashed with the v1.01pOTA
