### ISSUE TITLE
I have a small problem here.

### ISSUE THREAD

**Issue by theng616** [KmanOz/Sonoff-HomeAssistant#3]
Hi, I do follow the steps and instruction to do the sonoff settings, but now the result is showing 'DHT read error'. Do you know any steps goes wrong will cause this issues?

**Comment by KmanOz** [comment]
Make sure the DHT is plugging into the socket correctly. Remove the top case and plug the DHT back in making sure it's all the way in. I have noticed that the hole in the plastic isn't big enough and the plug does not seat properly in the socket. I had the same issue.

**Comment by theng616** [comment]
It works!! Thanks for helping!!
