### ISSUE TITLE
Support for Sonoff Dual

### ISSUE THREAD

**Issue by adrian-ludwig** [KmanOz/Sonoff-HomeAssistant#8]
Hi!
Is there any chance that this firmware will support Sonoff Dual ?

**Comment by KmanOz** [comment]
I have one here and haven't tackled it even though it wouldn't take very long to get going. I think because for a beginner they are a little more difficult to program. I will get onto it though to complete the Sonoff line up.

**Comment by KmanOz** [comment]
Sorry I have no plans to support a DUAL at this stage.
